spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:postgresql://postgres:5432/urlshortener
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    
server:
  port: 8080

url-shortener:
  base-url: http://5.187.7.225:8080/
  cache:
    ttl-hours: 24
  security:
    jwt:
      secret-key: ${JWT_SECRET:my_secret_key_at_least_32_chars_long}
      expiration-time: 86400000 # 24 hours in milliseconds
      refresh-token-expiration: 604800000 # 7 days in milliseconds 